# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.AzureAppService_ContainerUsername_020e8a702aea40be86229d91fbd8ceb5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_95b763cce4644fb4858946d919e7feaa }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2.2.1
      with:
        context: .
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_020e8a702aea40be86229d91fbd8ceb5 }}/danskebank-task:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'danskebank-task'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_54bf38b49d9c4fbb943579b070c424c7 }}
        images: '${{ secrets.AzureAppService_ContainerUsername_020e8a702aea40be86229d91fbd8ceb5 }}/danskebank-task:${{ github.sha }}'
